name: Java CI

on:
  push:
    branches:
      - release
      - stage
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/gitlab-ci-action@0.0.1
      - name: Trigger GitLab CI
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
